#pragma once
#include <cstdint>

// THIS FILE IS AUTO-GENERATED BY gen_i18n.py. DO NOT EDIT.
// clang-format off

// Forward declarations for flat string data blobs and offset tables
namespace i18n_strings {
extern const char STRINGS_EN_DATA[];
extern const uint16_t OFFSETS_EN[];
extern const char STRINGS_ES_DATA[];
extern const uint16_t OFFSETS_ES[];
extern const char STRINGS_FRENCH_DATA[];
extern const uint16_t OFFSETS_FRENCH[];
extern const char STRINGS_DE_DATA[];
extern const uint16_t OFFSETS_DE[];
extern const char STRINGS_CZECH_DATA[];
extern const uint16_t OFFSETS_CZECH[];
extern const char STRINGS_PORTUGUESE_DATA[];
extern const uint16_t OFFSETS_PORTUGUESE[];
extern const char STRINGS_RUSSIAN_DATA[];
extern const uint16_t OFFSETS_RUSSIAN[];
extern const char STRINGS_SV_DATA[];
extern const uint16_t OFFSETS_SV[];
extern const char STRINGS_RO_DATA[];
extern const uint16_t OFFSETS_RO[];
extern const char STRINGS_CA_DATA[];
extern const uint16_t OFFSETS_CA[];
extern const char STRINGS_UK_DATA[];
extern const uint16_t OFFSETS_UK[];
extern const char STRINGS_BE_DATA[];
extern const uint16_t OFFSETS_BE[];
extern const char STRINGS_IT_DATA[];
extern const uint16_t OFFSETS_IT[];
extern const char STRINGS_PL_DATA[];
extern const uint16_t OFFSETS_PL[];
extern const char STRINGS_FI_DATA[];
extern const uint16_t OFFSETS_FI[];
extern const char STRINGS_DA_DATA[];
extern const uint16_t OFFSETS_DA[];
extern const char STRINGS_NL_DATA[];
extern const uint16_t OFFSETS_NL[];
extern const char STRINGS_TR_DATA[];
extern const uint16_t OFFSETS_TR[];
extern const char STRINGS_KK_DATA[];
extern const uint16_t OFFSETS_KK[];
extern const char STRINGS_HU_DATA[];
extern const uint16_t OFFSETS_HU[];
extern const char STRINGS_LT_DATA[];
extern const uint16_t OFFSETS_LT[];
extern const char STRINGS_SI_DATA[];
extern const uint16_t OFFSETS_SI[];
extern const char STRINGS_VI_DATA[];
extern const uint16_t OFFSETS_VI[];
}  // namespace i18n_strings

// Language enum
enum class Language : uint8_t {
  EN = 0,
  ES = 1,
  FRENCH = 2,
  DE = 3,
  CZECH = 4,
  PORTUGUESE = 5,
  RUSSIAN = 6,
  SV = 7,
  RO = 8,
  CA = 9,
  UK = 10,
  BE = 11,
  IT = 12,
  PL = 13,
  FI = 14,
  DA = 15,
  NL = 16,
  TR = 17,
  KK = 18,
  HU = 19,
  LT = 20,
  SI = 21,
  VI = 22,
  _COUNT
};

// Language codes (defined in I18nStrings.cpp)
extern const char* const LANGUAGE_CODES[];

// Language display names (defined in I18nStrings.cpp)
extern const char* const LANGUAGE_NAMES[];

// Character sets for each language (defined in I18nStrings.cpp)
extern const char* const CHARACTER_SETS[];

// String IDs
enum class StrId : uint16_t {
  STR_CROSSPOINT,
  STR_BOOTING,
  STR_FILE_TRANSFER,
  STR_SETTINGS_TITLE,
  STR_NO_OPEN_BOOK,
  STR_START_READING,
  STR_BOOKS,
  STR_NO_FILES_FOUND,
  STR_SELECT_CHAPTER,
  STR_END_OF_BOOK,
  STR_EMPTY_CHAPTER,
  STR_INDEXING,
  STR_PAGE_LOAD_ERROR,
  STR_EMPTY_FILE,
  STR_OUT_OF_BOUNDS,
  STR_LOADING,
  STR_LOADING_POPUP,
  STR_LOAD_EPUB_FAILED,
  STR_WIFI_NETWORKS,
  STR_NO_NETWORKS,
  STR_NETWORKS_FOUND,
  STR_SCANNING,
  STR_CONNECTING,
  STR_CONNECTED,
  STR_CONNECTION_FAILED,
  STR_FORGET_NETWORK,
  STR_SAVE_PASSWORD,
  STR_PRESS_OK_SCAN,
  STR_JOIN_NETWORK,
  STR_CREATE_HOTSPOT,
  STR_JOIN_DESC,
  STR_HOTSPOT_DESC,
  STR_STARTING_HOTSPOT,
  STR_HOTSPOT_MODE,
  STR_CONNECT_WIFI_HINT,
  STR_OPEN_URL_HINT,
  STR_OR_HTTP_PREFIX,
  STR_SCAN_QR_HINT,
  STR_CALIBRE_WIRELESS,
  STR_CALIBRE_WEB_URL,
  STR_NETWORK_LEGEND,
  STR_MAC_ADDRESS,
  STR_CHECKING_WIFI,
  STR_ENTER_WIFI_PASSWORD,
  STR_TO_PREFIX,
  STR_CAT_DISPLAY,
  STR_CAT_READER,
  STR_CAT_CONTROLS,
  STR_CAT_SYSTEM,
  STR_SLEEP_SCREEN,
  STR_SLEEP_SMART,
  STR_SLEEP_COVER_MODE,
  STR_HIDE_BATTERY,
  STR_EXTRA_SPACING,
  STR_FORCE_PARAGRAPH_INDENTS,
  STR_TEXT_AA,
  STR_IMAGES,
  STR_IMAGES_DISPLAY,
  STR_IMAGES_PLACEHOLDER,
  STR_IMAGES_SUPPRESS,
  STR_SHORT_PWR_BTN,
  STR_ORIENTATION,
  STR_SIDE_BTN_LAYOUT,
  STR_ORIENTATION_AWARE,
  STR_NAV_BUTTONS,
  STR_ALL_BUTTONS,
  STR_SIDE_BTN_LONG_PRESS,
  STR_CHAPTER_SKIP_OPT,
  STR_CHANGE_FONT_SIZE,
  STR_LONG_PRESS_BEHAVIOR,
  STR_LONG_PRESS_BEHAVIOR_OFF,
  STR_LONG_PRESS_BEHAVIOR_SKIP,
  STR_LONG_PRESS_BEHAVIOR_ORIENTATION,
  STR_FONT_FAMILY,
  STR_FONT_SIZE,
  STR_LINE_SPACING,
  STR_SCREEN_MARGIN,
  STR_PARA_ALIGNMENT,
  STR_HYPHENATION,
  STR_TIME_TO_SLEEP,
  STR_SHOW_HIDDEN_FILES,
  STR_TOGGLE_HIDDEN_FILES_HINT,
  STR_DEVELOPER_MODE,
  STR_REFRESH_FREQ,
  STR_KOREADER_SYNC,
  STR_CHECK_UPDATES,
  STR_LANGUAGE,
  STR_FACTORY_RESET,
  STR_SWITCH_TO_TRMNL,
  STR_CLEAR_READING_CACHE,
  STR_USERNAME,
  STR_PASSWORD,
  STR_SYNC_SERVER_URL,
  STR_DOCUMENT_MATCHING,
  STR_KOREADER_USERNAME,
  STR_KOREADER_PASSWORD,
  STR_FILENAME,
  STR_BINARY,
  STR_WIFI_CONN_FAILED,
  STR_DONE,
  STR_CLEAR_CACHE_WARNING_1,
  STR_CLEAR_CACHE_WARNING_2,
  STR_CLEAR_CACHE_WARNING_3,
  STR_CLEAR_CACHE_WARNING_4,
  STR_CLEARING_CACHE,
  STR_CACHE_CLEARED,
  STR_ITEMS_REMOVED,
  STR_FAILED_LOWER,
  STR_CLEAR_CACHE_FAILED,
  STR_CHECK_SERIAL_OUTPUT,
  STR_DARK,
  STR_LIGHT,
  STR_FOLLOW_THEME,
  STR_CUSTOM,
  STR_SLEEP_SOURCE,
  STR_POKEDEX,
  STR_ALL,
  STR_NONE_OPT,
  STR_FIT,
  STR_CROP,
  STR_NEVER,
  STR_IN_READER,
  STR_ALWAYS,
  STR_IGNORE,
  STR_SLEEP,
  STR_PAGE_TURN,
  STR_FORCE_REFRESH,
  STR_CHANGE_FONT,
  STR_PORTRAIT,
  STR_LANDSCAPE_CW,
  STR_INVERTED,
  STR_LANDSCAPE_CCW,
  STR_PREV_NEXT,
  STR_NEXT_PREV,
  STR_NOTO_SERIF,
  STR_NOTO_SANS,
  STR_OPEN_DYSLEXIC,
  STR_SMALL,
  STR_MEDIUM,
  STR_LARGE,
  STR_X_LARGE,
  STR_TIGHT,
  STR_NORMAL,
  STR_WIDE,
  STR_JUSTIFY,
  STR_ALIGN_LEFT,
  STR_CENTER,
  STR_ALIGN_RIGHT,
  STR_PAGES_1,
  STR_PAGES_5,
  STR_PAGES_10,
  STR_PAGES_15,
  STR_PAGES_30,
  STR_UPDATE,
  STR_INSTALL,
  STR_CURRENT_VERSION,
  STR_NEW_VERSION,
  STR_UPDATING,
  STR_UPDATE_FAILED,
  STR_UPDATE_COMPLETE,
  STR_LOCAL_UPDATE_FOUND,
  STR_LOCAL_UPDATE_PROMPT,
  STR_SKIP_FOR_NOW,
  STR_SKIP_THIS_VERSION,
  STR_DELETE_IT,
  STR_RESTARTING_HINT,
  STR_EXTERNAL_FONT,
  STR_NO_ENTRIES,
  STR_DOWNLOADING,
  STR_DOWNLOAD_FAILED,
  STR_ERROR_MSG,
  STR_UNNAMED,
  STR_NO_SERVER_URL,
  STR_FETCH_FEED_FAILED,
  STR_PARSE_FEED_FAILED,
  STR_NEXT_PAGE,
  STR_PREV_PAGE,
  STR_NETWORK_PREFIX,
  STR_IP_ADDRESS_PREFIX,
  STR_SCAN_QR_WIFI_HINT,
  STR_ERROR_GENERAL_FAILURE,
  STR_ERROR_NETWORK_NOT_FOUND,
  STR_ERROR_CONNECTION_TIMEOUT,
  STR_SD_CARD,
  STR_BACK,
  STR_EXIT,
  STR_HOME,
  STR_SAVE,
  STR_SELECT,
  STR_SELECTED,
  STR_TOGGLE,
  STR_CONFIRM,
  STR_CANCEL,
  STR_CONNECT,
  STR_OPEN,
  STR_DOWNLOAD,
  STR_RETRY,
  STR_YES,
  STR_NO,
  STR_SHOW,
  STR_HIDE,
  STR_STATE_ON,
  STR_STATE_OFF,
  STR_NOT_SET,
  STR_DIR_LEFT,
  STR_DIR_RIGHT,
  STR_DIR_UP,
  STR_DIR_DOWN,
  STR_OK_BUTTON,
  STR_SLEEP_COVER_FILTER,
  STR_SLEEP_CYCLE_MODE,
  STR_RANDOM,
  STR_SEQUENTIAL,
  STR_FILTER_CONTRAST,
  STR_CUSTOMISE_STATUS_BAR,
  STR_CHAPTER_PAGE_COUNT,
  STR_BOOK_PROGRESS_PERCENTAGE,
  STR_PROGRESS_BAR,
  STR_PROGRESS_BAR_THICKNESS,
  STR_PROGRESS_BAR_THIN,
  STR_PROGRESS_BAR_MEDIUM,
  STR_PROGRESS_BAR_THICK,
  STR_BOOK,
  STR_CHAPTER,
  STR_EXAMPLE_CHAPTER,
  STR_EXAMPLE_BOOK,
  STR_PREVIEW,
  STR_TITLE,
  STR_BATTERY,
  STR_UI_THEME,
  STR_THEME_CLASSIC,
  STR_THEME_LYRA,
  STR_THEME_LYRA_EXTENDED,
  STR_THEME_FORK_DRIFT,
  STR_THEME_POKEMON_PARTY,
  STR_THEME_MINIMAL,
  STR_PARTY,
  STR_PARTY_SUBTITLE,
  STR_PARTY_EMPTY,
  STR_PARTY_LV,
  STR_SUNLIGHT_FADING_FIX,
  STR_REMAP_FRONT_BUTTONS,
  STR_OPDS_BROWSER,
  STR_SEARCH,
  STR_RECENT_BOOKS_VIEW,
  STR_LIST_VIEW,
  STR_GRID_VIEW,
  STR_MENU_RECENT_BOOKS,
  STR_NO_RECENT_BOOKS,
  STR_CALIBRE_DESC,
  STR_FORGET_AND_REMOVE,
  STR_FORGET_BUTTON,
  STR_CLEAR_BUTTON,
  STR_GO_TO_PERCENT,
  STR_GO_HOME_BUTTON,
  STR_SYNC_PROGRESS,
  STR_DELETE_CACHE,
  STR_DELETE,
  STR_DISPLAY_QR,
  STR_CHAPTER_PREFIX,
  STR_PAGES_SEPARATOR,
  STR_BOOK_PREFIX,
  STR_CALIBRE_URL_HINT,
  STR_SYNCING_TIME,
  STR_CALC_HASH,
  STR_HASH_FAILED,
  STR_FETCH_PROGRESS,
  STR_UPLOAD_PROGRESS,
  STR_NO_CREDENTIALS_MSG,
  STR_KOREADER_SETUP_HINT,
  STR_PROGRESS_FOUND,
  STR_REMOTE_LABEL,
  STR_LOCAL_LABEL,
  STR_PAGE_OVERALL_FORMAT,
  STR_PAGE_TOTAL_OVERALL_FORMAT,
  STR_DEVICE_FROM_FORMAT,
  STR_APPLY_REMOTE,
  STR_UPLOAD_LOCAL,
  STR_NO_REMOTE_MSG,
  STR_UPLOAD_PROMPT,
  STR_UPLOAD_SUCCESS,
  STR_SYNC_FAILED_MSG,
  STR_SAVE_PROGRESS_FAILED,
  STR_SECTION_PREFIX,
  STR_UPLOAD,
  STR_BOOK_S_STYLE,
  STR_EMBEDDED_STYLE,
  STR_FOCUS_READING,
  STR_GUIDE_READING,
  STR_OPDS_SERVER_URL,
  STR_DARK_MODE,
  STR_BACKGROUND_SERVER,
  STR_ONLY_ON_CHARGE,
  STR_BACKGROUND_SERVER_WARNING_TITLE,
  STR_BACKGROUND_SERVER_WARNING_BODY,
  STR_VALIDATE_SLEEP_IMAGES,
  STR_DEVICE_NAME,
  STR_SET_SLEEP_COVER,
  STR_FOOTNOTES,
  STR_NO_FOOTNOTES,
  STR_LINK,
  STR_SCREENSHOT_BUTTON,
  STR_ADD_SERVER,
  STR_SERVER_NAME,
  STR_NO_SERVERS,
  STR_DELETE_SERVER,
  STR_OPDS_SERVERS,
  STR_AUTO_TURN_ENABLED,
  STR_AUTO_TURN_PAGES_PER_MIN,
  STR_AUTO_TURN_STEP_HINT,
  STR_SLEEP_TIMER_VALUE_FORMAT,
  STR_SLEEP_TIMER_STEP_HINT,
  STR_TRANSPARENT,
  STR_NOTES,
  STR_NOTES_EMPTY,
  STR_ADD_NOTE,
  STR_ADD_TO_ANKI,
  STR_ANKI_CARDS,
  STR_ANKI_NO_CARDS,
  STR_ANKI_ADD_HINT,
  STR_ANKI_FRONT,
  STR_ANKI_BACK,
  STR_ANKI_SOURCE_PREFIX,
  STR_ANKI_SAVED,
  STR_ANKI_SAVE_PROMPT,
  STR_GLOBAL_STATUS_BAR,
  STR_OFF,
  STR_ON,
  STR_NO_SLEEP,
  STR_STATUS_BAR_POSITION,
  STR_STATUS_BAR_TOP,
  STR_STATUS_BAR_BOTTOM,
  STR_MANAGE_FONTS,
  STR_FONT_BROWSER,
  STR_LOADING_FONT_LIST,
  STR_NO_FONTS_AVAILABLE,
  STR_FONT_INSTALLED,
  STR_FONT_INSTALL_FAILED,
  STR_INSTALLED,
  STR_DOWNLOAD_ALL,
  STR_UPDATE_ALL,
  STR_UPDATE_AVAILABLE,
  STR_CRASH_TITLE,
  STR_CRASH_DESCRIPTION,
  STR_CRASH_REASON,
  STR_CRASH_NO_REASON,
  STR_KB_HINT_MOVE_CURSOR,
  STR_KB_HINT_RETURN_CURSOR,
  STR_KB_HINT_HIDE_PASSWORD,
  STR_KB_HINT_SHOW_PASSWORD,
  STR_KB_HINT_TOGGLE_HIDE_PASSWORD,
  STR_KB_HINT_TOGGLE_SHOW_PASSWORD,
  STR_KB_HINT_EDIT_ENTRY,
  STR_KB_TIPS,
  STR_KB_HINT_RETURN_KEYBOARD,
  STR_KB_HINT_EXIT_URL_MODE,
  STR_KB_HINT_CLEAR_TEXT,
  STR_KB_HINT_SECONDARY_CHAR,
  STR_KB_HINT_UPPER_SECONDARY,
  STR_KB_HINT_LOWER_SECONDARY,
  STR_KB_HINT_URL_SNIPPETS,
  STR_CAT_TIME,
  STR_TIME_MODE,
  STR_TIME_UTC,
  STR_TIME_LOCAL,
  STR_TIME_MANUAL,
  STR_TIMEZONE_OFFSET,
  STR_SD_FIRMWARE_UPDATE,
  STR_SELECT_FIRMWARE_FILE,
  STR_NO_BIN_FILES,
  STR_VALIDATING_FIRMWARE,
  STR_INVALID_FIRMWARE,
  STR_FIRMWARE_TOO_LARGE,
  STR_FIRMWARE_TOO_SMALL,
  STR_FIRMWARE_UPDATE_PROMPT,
  STR_FIRMWARE_FILE_OPEN_FAILED,
  STR_FIRMWARE_WRITE_FAILED,
  STR_FIRMWARE_UPDATE_DO_NOT_POWER_OFF,
  STR_RECOVERY_MODE,
  STR_RECOVERY_MODE_HINT,
  STR_LONG_PRESS_MENU_ACTION,
  STR_TOGGLE_GUIDE_DOTS,
  STR_TOGGLE_BIONIC_READING,
  STR_TOGGLE_BOOKMARK,
  STR_MARK_FINISHED,
  STR_READING_STATS,
  STR_STATS_LESS_THAN_MIN,
  STR_STATS_THIS_BOOK,
  STR_STATS_AVERAGES,
  STR_STATS_PAGES_PER_MIN,
  STR_STATS_SESSIONS_LBL,
  STR_STATS_TIME_LBL,
  STR_STATS_PAGES_LBL,
  STR_STATS_AVG_SESSION_LBL,
  STR_CYCLE_PAGE_TURN,
  STR_POWER_BUTTON,
  STR_FRONT_BUTTONS,
  STR_SIDE_BUTTONS,
  STR_LONG_PRESS_ACTION,
  // Sentinel - must be last
  _COUNT
};

// Holds a flat string blob and its offset table for one language
struct LangStrings {
  const char* data;
  const uint16_t* offsets;
};

// Helper function to get string data for a language
inline LangStrings getLanguageStrings(Language lang) {
  switch (lang) {
    case Language::EN:
      return {i18n_strings::STRINGS_EN_DATA, i18n_strings::OFFSETS_EN};
    case Language::ES:
      return {i18n_strings::STRINGS_ES_DATA, i18n_strings::OFFSETS_ES};
    case Language::FRENCH:
      return {i18n_strings::STRINGS_FRENCH_DATA, i18n_strings::OFFSETS_FRENCH};
    case Language::DE:
      return {i18n_strings::STRINGS_DE_DATA, i18n_strings::OFFSETS_DE};
    case Language::CZECH:
      return {i18n_strings::STRINGS_CZECH_DATA, i18n_strings::OFFSETS_CZECH};
    case Language::PORTUGUESE:
      return {i18n_strings::STRINGS_PORTUGUESE_DATA, i18n_strings::OFFSETS_PORTUGUESE};
    case Language::RUSSIAN:
      return {i18n_strings::STRINGS_RUSSIAN_DATA, i18n_strings::OFFSETS_RUSSIAN};
    case Language::SV:
      return {i18n_strings::STRINGS_SV_DATA, i18n_strings::OFFSETS_SV};
    case Language::RO:
      return {i18n_strings::STRINGS_RO_DATA, i18n_strings::OFFSETS_RO};
    case Language::CA:
      return {i18n_strings::STRINGS_CA_DATA, i18n_strings::OFFSETS_CA};
    case Language::UK:
      return {i18n_strings::STRINGS_UK_DATA, i18n_strings::OFFSETS_UK};
    case Language::BE:
      return {i18n_strings::STRINGS_BE_DATA, i18n_strings::OFFSETS_BE};
    case Language::IT:
      return {i18n_strings::STRINGS_IT_DATA, i18n_strings::OFFSETS_IT};
    case Language::PL:
      return {i18n_strings::STRINGS_PL_DATA, i18n_strings::OFFSETS_PL};
    case Language::FI:
      return {i18n_strings::STRINGS_FI_DATA, i18n_strings::OFFSETS_FI};
    case Language::DA:
      return {i18n_strings::STRINGS_DA_DATA, i18n_strings::OFFSETS_DA};
    case Language::NL:
      return {i18n_strings::STRINGS_NL_DATA, i18n_strings::OFFSETS_NL};
    case Language::TR:
      return {i18n_strings::STRINGS_TR_DATA, i18n_strings::OFFSETS_TR};
    case Language::KK:
      return {i18n_strings::STRINGS_KK_DATA, i18n_strings::OFFSETS_KK};
    case Language::HU:
      return {i18n_strings::STRINGS_HU_DATA, i18n_strings::OFFSETS_HU};
    case Language::LT:
      return {i18n_strings::STRINGS_LT_DATA, i18n_strings::OFFSETS_LT};
    case Language::SI:
      return {i18n_strings::STRINGS_SI_DATA, i18n_strings::OFFSETS_SI};
    case Language::VI:
      return {i18n_strings::STRINGS_VI_DATA, i18n_strings::OFFSETS_VI};
    default:
      return {i18n_strings::STRINGS_EN_DATA, i18n_strings::OFFSETS_EN};
  }
}

// Helper function to get language count
constexpr uint8_t getLanguageCount() { return static_cast<uint8_t>(Language::_COUNT); }

// Sorted language indices by code (auto-generated by gen_i18n.py)
// Order: English, Беларуская, Català, Čeština, Dansk, Deutsch, Español, Suomi, Français, Magyar, Italiano, Қазақша
// Lietuvių, Nederlands, Polski, Português (Brasil), Română, Русский, Slovenščina, Svenska, Türkçe, Українська
// clang-format off
// Tiếng Việt
constexpr uint8_t SORTED_LANGUAGE_INDICES[] = {static_cast<uint8_t>(Language::EN), static_cast<uint8_t>(Language::BE), static_cast<uint8_t>(Language::CA), static_cast<uint8_t>(Language::CZECH), static_cast<uint8_t>(Language::DA), static_cast<uint8_t>(Language::DE), static_cast<uint8_t>(Language::ES), static_cast<uint8_t>(Language::FI), static_cast<uint8_t>(Language::FRENCH), static_cast<uint8_t>(Language::HU), static_cast<uint8_t>(Language::IT), static_cast<uint8_t>(Language::KK), static_cast<uint8_t>(Language::LT), static_cast<uint8_t>(Language::NL), static_cast<uint8_t>(Language::PL), static_cast<uint8_t>(Language::PORTUGUESE), static_cast<uint8_t>(Language::RO), static_cast<uint8_t>(Language::RUSSIAN), static_cast<uint8_t>(Language::SI), static_cast<uint8_t>(Language::SV), static_cast<uint8_t>(Language::TR), static_cast<uint8_t>(Language::UK), static_cast<uint8_t>(Language::VI)};
// clang-format on

static_assert(sizeof(SORTED_LANGUAGE_INDICES) / sizeof(SORTED_LANGUAGE_INDICES[0]) == getLanguageCount(),
              "SORTED_LANGUAGE_INDICES size mismatch");

// V1 language.bin migration table (frozen enum order from 2f969a9)
constexpr Language V1_LANGUAGES[] = {
    Language::EN, Language::ES, Language::FRENCH, Language::DE, Language::CZECH, Language::PORTUGUESE, Language::RUSSIAN, Language::SV, Language::RO, Language::CA, Language::UK, Language::BE, Language::IT, Language::PL, Language::FI, Language::DA, Language::NL, Language::TR, Language::KK, Language::HU, Language::LT, Language::SI,
};
constexpr uint8_t V1_LANGUAGE_COUNT = 22;
