#!/usr/bin/env python3
"""Generate deterministic tooling artifacts from config/features.yaml."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tempfile
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).parent))
import feature_manifest


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "config" / "features.yaml"
OUTPUT_PATHS = (
    Path("docs/configurator/features.generated.js"),
    Path("config/profile-matrix.generated.json"),
)
NOTICE = "Generated by scripts/generate_feature_artifacts.py; DO NOT EDIT."


def _semantic_manifest(manifest: feature_manifest.FeatureManifest) -> dict[str, Any]:
    """Return the order-independent manifest data covered by the digest."""
    return {
        "schema_version": manifest.schema_version,
        "features": {
            key: {
                "macro": record.macro,
                "label": record.label,
                "description": record.description,
                "estimated_size_kib": record.estimated_size_kib,
                "implemented": record.implemented,
                "stable": record.stable,
                "requires_all": list(record.requires_all),
                "requires_any": list(record.requires_any),
                "conflicts": list(record.conflicts),
                "recommends": list(record.recommends),
            }
            for key, record in sorted(manifest.features.items())
        },
        "profiles": {
            name: {
                "description": record.description,
                "extends": record.extends,
                "features": dict(sorted(record.features.items())),
            }
            for name, record in sorted(manifest.profiles.items())
        },
    }


def manifest_digest(manifest: feature_manifest.FeatureManifest) -> str:
    canonical = json.dumps(
        _semantic_manifest(manifest),
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest()


def _json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True)


def generate_js(manifest: feature_manifest.FeatureManifest, digest: str) -> str:
    features = {
        key: {
            "flag": record.macro,
            "implemented": record.implemented,
            "sizeKb": record.estimated_size_kib,
            "stable": record.stable,
        }
        for key, record in sorted(manifest.features.items())
    }
    docs = {
        key: record.description
        for key, record in sorted(manifest.features.items())
    }
    dependencies = {
        key: list(record.requires_all)
        for key, record in sorted(manifest.features.items())
        if record.requires_all
    }
    dependencies_any = {
        key: list(record.requires_any)
        for key, record in sorted(manifest.features.items())
        if record.requires_any
    }
    profiles = {
        name: dict(sorted(manifest.profiles[name].features.items()))
        for name in sorted(manifest.profiles)
    }

    lines = [
        f"// {NOTICE}",
        f"// Manifest digest: sha256:{digest}",
        f"const FEATURES = {_json(features)};",
        f"const FEATURE_DOCS = {_json(docs)};",
        f"const FEATURE_DEPENDENCIES = {_json(dependencies)};",
        f"const FEATURE_DEPENDENCIES_ANY = {_json(dependencies_any)};",
        f"const PROFILES = {_json(profiles)};",
    ]
    return "\n".join(lines) + "\n"


def generate_matrix(manifest: feature_manifest.FeatureManifest, digest: str) -> str:
    matrix = {
        "_generated": {
            "notice": NOTICE,
            "manifest_digest": f"sha256:{digest}",
        },
        "schema_version": manifest.schema_version,
        "profiles": {
            name: {
                "description": manifest.profiles[name].description,
                "features": dict(sorted(manifest.resolve_profile(name).items())),
            }
            for name in sorted(manifest.profiles)
        },
    }
    return _json(matrix) + "\n"


def generate_outputs(manifest: feature_manifest.FeatureManifest) -> dict[Path, bytes]:
    digest = manifest_digest(manifest)
    return {
        OUTPUT_PATHS[0]: generate_js(manifest, digest).encode("utf-8"),
        OUTPUT_PATHS[1]: generate_matrix(manifest, digest).encode("utf-8"),
    }


def write_outputs(output_root: Path, outputs: dict[Path, bytes]) -> None:
    for relative_path, content in outputs.items():
        destination = output_root / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(content)


def check_outputs(output_root: Path, outputs: dict[Path, bytes]) -> int:
    """Generate in a temporary root, then byte-compare with checked-in files."""
    stale: list[Path] = []
    with tempfile.TemporaryDirectory(prefix="feature-artifacts-") as temp_dir:
        temp_root = Path(temp_dir)
        write_outputs(temp_root, outputs)
        for relative_path in OUTPUT_PATHS:
            expected = (temp_root / relative_path).read_bytes()
            destination = output_root / relative_path
            if not destination.is_file() or destination.read_bytes() != expected:
                stale.append(relative_path)

    if stale:
        print("Generated feature artifacts are missing or stale:")
        for relative_path in stale:
            print(f"  {relative_path}")
        print("Run: uv run python scripts/generate_feature_artifacts.py")
        return 1

    print("Generated feature artifacts are up to date.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Generate in a temporary directory and verify byte-equivalent outputs",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=ROOT,
        help="Repository-shaped output root (default: repository root)",
    )
    args = parser.parse_args()

    try:
        manifest = feature_manifest.load_manifest(MANIFEST_PATH)
        outputs = generate_outputs(manifest)
    except (OSError, ValueError) as error:
        print(f"Error loading feature manifest: {error}", file=sys.stderr)
        return 1

    output_root = args.output_root.resolve()
    if args.check:
        return check_outputs(output_root, outputs)

    write_outputs(output_root, outputs)
    for relative_path in OUTPUT_PATHS:
        print(f"Generated {output_root / relative_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
